spring:
  application:
    name: resuelve-api

  profiles:
    active: dev  # por defecto usas local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate


  server:
    port: 8080

  management:
    endpoints:
      web:
        exposure:
          include: health,metrics
    endpoint:
      health:
        show-details:always
<<<<<<< HEAD
=======



>>>>>>> 364920ad99d98704e154d6362bdf6f43ef6ed284
